// XXX: This file is generated by "scripts/create-pronunciations.js"
import React from 'react';
import PronunciationWord from '../components/PronunciationWord';
export default () => (<div>
  <section>
    <h3>前端框架</h3>
    <div>
      <PronunciationWord word="redux" ipa="riː'dʌks" />
      <PronunciationWord word="yarn" ipa="jɑːrn" />
      <PronunciationWord word="gulp" ipa="ɡʌlp" />
      <PronunciationWord word="grunt" ipa="ɡrʌnt" />
      <PronunciationWord word="angular" ipa="'æŋɡjələr" />
      <PronunciationWord word="polymer" ipa="ˈpɒlᵻmər" />
      <PronunciationWord word="brunch" ipa="brʌntʃ" />
      <PronunciationWord word="react" ipa="ri'ækt" />
      <PronunciationWord word="jasmine" ipa="'dʒæzmɪn" />
      <PronunciationWord word="jest" ipa="dʒɛst" />
      <PronunciationWord word="backbone" ipa="ˈbækˌboʊn" />
      <PronunciationWord word="mocha" ipa="ˈmoʊ kə" />
      <PronunciationWord word="vue" ipa="vjuː" />
    </div>
  </section>
  <section>
    <h3>其他技术</h3>
    <div>
      <PronunciationWord word="Laravel" ipa="'lærəvel" />
      <PronunciationWord word="github" ipa="ɡɪthʌb" />
      <PronunciationWord word="azure" ipa="ˈæʒɚ" />
      <PronunciationWord word="electron" ipa="ɪ'lektrɑːn" />
      <PronunciationWord word="ionic" ipa="aɪ'ɑːnɪk" />
      <PronunciationWord word="boilerplate" ipa="ˈbɔɪləˌpleɪt" />
      <PronunciationWord word="nuclide" ipa="ˈnjuːklaɪd" />
      <PronunciationWord word="atom" ipa="ˈæt əm" />
      <PronunciationWord word="YAML" ipa="ˈjæməl" />
      <PronunciationWord word="elixir" ipa="ɪˈlɪk sər" />
    </div>
  </section>
</div>)