// XXX: This file is generated by "scripts/create-pronunciations.js"
import React from 'react';
import PronunciationWord from '../components/PronunciationWord';
export default () => (<div>
  <section>
    <h3>前端框架</h3>
    <div>
      <PronunciationWord word="redux" ipa="riː'dʌks" />
      <PronunciationWord word="gulp" ipa="ɡʌlp" />
      <PronunciationWord word="grunt" ipa="ɡrʌnt" />
      <PronunciationWord word="angular" ipa="'æŋɡjələr" />
    </div>
  </section>
  <section>
    <h3>其他技术</h3>
    <div>
      <PronunciationWord word="Laravel" ipa="'lærəvel" />
      <PronunciationWord word="github" ipa="ɡɪthʌb" />
      <PronunciationWord word="azure" ipa="ˈæʒɚ" />
    </div>
  </section>
</div>)